name: Publish Docker image (Bionic)

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/build-bionic.yml"
      - "bionic/**"
      - "common/**"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./bionic/Dockerfile
          push: true
          tags: onionyst/ubuntu-dev:bionic
      - name: Send notification to Slack
        id: slack
        if: ${{ always() }}
        uses: onionyst/action-slack-notify@v1.0
        env:
          SLACK_AUTHOR: ${{ github.event.head_commit.author.name }}
          SLACK_AVATAR_URL: ${{ github.event.repository.owner.avatar_url }}
          SLACK_COMMIT_ID: ${{ github.event.head_commit.id }}
          SLACK_COMMIT_MSG: ${{ github.event.head_commit.message }}
          SLACK_COMMIT_URL: ${{ github.event.head_commit.url }}
          SLACK_COMPARE_URL: ${{ github.event.compare }}
          SLACK_EMAIL: ${{ github.event.head_commit.author.email }}
          SLACK_STATUS: ${{ job.status }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
